In [ ]:
import torch 
import numpy as np
import torch.nn as nn
import torch.optim as optim
torch.__version__

'2.11.0+cpu'

Setting

In [ ]:
x = torch.tensor([1,2,3,4,5])
x

tensor([1, 2, 3, 4, 5])

In [ ]:
x = torch.tensor([[1,2],[1,4]])
x

tensor([[1, 2],
        [1, 4]])

In [ ]:
x = torch.zeros(3,2)
x

tensor([[0., 0.],
        [0., 0.],
        [0., 0.]])

In [ ]:
x = torch.ones(3,2)
x

tensor([[1., 1.],
        [1., 1.],
        [1., 1.]])

In [ ]:
x = torch.rand(3,2)
x

tensor([[0.1830, 0.1783],
        [0.3162, 0.8312],
        [0.2753, 0.8408]])

In [ ]:
x = torch.tensor([
    [1,2],
    [1,4]
])
x.shape

torch.Size([2, 2])

In [ ]:
x = torch.tensor([1,2,3,4,5])
x[3]

tensor(4)

In [ ]:
x = torch.tensor([
    [1,2],
    [3,4]
])
x[1][0]

tensor(3)

In [ ]:
x = torch.tensor([
    [1,2],
    [3,4]
])
x[1,0]

tensor(3)

In [ ]:
a = torch.tensor([1,2,3])
b = torch.tensor([1,2,3])

a+b

tensor([2, 4, 6])

In [ ]:
a = torch.tensor([1,2,3])
b = 2

a+b

tensor([3, 4, 5])

In [ ]:
arr = np.array([1,2,3,4,5])
ten = torch.from_numpy(arr)

ten

tensor([1, 2, 3, 4, 5])

Auto

In [ ]:
x = torch.tensor(3.0,requires_grad=True)
x

tensor(3., requires_grad=True)

In [ ]:
x = torch.tensor(3.0,requires_grad=True)
y = torch.tensor(2.0)
w = x + y
w

tensor(5., grad_fn=<AddBackward0>)

In [ ]:
x = torch.tensor(3.0,requires_grad=True)
y = torch.tensor(2.0)
y_pred = x * y
y_true = torch.tensor(10.0) 

loss = (y_pred - y_true) **2
loss

tensor(16., grad_fn=<PowBackward0>)

In [ ]:
x = torch.tensor(3.0,requires_grad=True)
y = torch.tensor(2.0)
y_pred = x * y
y_true = torch.tensor(10.0) 

loss = (y_pred - y_true) **2
loss.backward()
x.grad

tensor(-16.)

In [ ]:
x = torch.tensor(2.0)
w = torch.tensor(3.0,requires_grad=True)
y_true = torch.tensor(10.0)
lr = 0.1
y_pred = w*x
loss = (y_true - y_pred)**2
loss.backward()
print("Before update")
print("w:", w.item())
print("loss", loss.item())
print("gradient", w.grad.item())
with torch.no_grad():
    w -= lr * w.grad
w.grad.zero_()
print("After update")
print("w:", w.item())


Before update
w: 3.0
loss 16.0
gradient -16.0
After update
w: 4.599999904632568


In [ ]:
x = torch.tensor([1,2,3,4])
y_true = torch.tensor([2,4,6,8])
w = torch.tensor(0.0,requires_grad=True)
lr = 0.1
epochs = 10
for epoch in range(epochs):
    y_pred = w*x
    loss = ((y_true-y_pred)**2).mean()
    loss.backward()
    with torch.no_grad():
        w -= lr * w.grad
    print(f"Epoch {epoch+1}: w = {w.item():.4f} , loss = {loss.item():.4f}")

Epoch 1: w = 3.0000 , loss = 30.0000
Epoch 2: w = 4.5000 , loss = 7.5000
Epoch 3: w = 2.2500 , loss = 46.8750
Epoch 4: w = -0.3750 , loss = 0.4688
Epoch 5: w = 0.5625 , loss = 42.3047
Epoch 6: w = 3.6562 , loss = 15.4980
Epoch 7: w = 4.2656 , loss = 20.5737
Epoch 8: w = 1.4766 , loss = 38.4979
Epoch 9: w = -0.5273 , loss = 2.0549
Epoch 10: w = 1.2598 , loss = 47.9060


In [ ]:
class Mymodel(nn.Module):
    def __init__(self):
        super().__init__()
        self.linear = nn.Linear(1,1)
    def forward(self,x):
        return self.linear(x)

x = torch.tensor([[1.], [2.], [3.], [4.]])
y = torch. tensor([[2.], [4.], [6.], [8.]])

model = Mymodel()
loss_fun = nn.MSELoss()
optimizer = optim.Adam(model.parameters(),lr = 0.1)

for epoch in range(10):
    optimizer.zero_grad()
    y_pred = model(x)
    loss = loss_fun(y_pred,y)
    loss.backward()
    optimizer.step()
    print(f"Epoch {epoch+1}: loss = {loss.item():.4f}")
torch.save(model.state_dict,"linear_model.pth")

Epoch 1: loss = 21.1186
Epoch 2: loss = 17.8801
Epoch 3: loss = 14.9203
Epoch 4: loss = 12.2429
Epoch 5: loss = 9.8499
Epoch 6: loss = 7.7414
Epoch 7: loss = 5.9147
Epoch 8: loss = 4.3642
Epoch 9: loss = 3.0813
Epoch 10: loss = 2.0535
